### PR TITLE
Scan Soft Button and text. APX 6K scan function 

### PR DESCRIPTION
**Pull request by Imwhattherel**

### CODE REVIEW

**Comment by Imwhattherel** [comment]
Finished Scan buttons, Added 6KXE

**Review by firealarmss — CHANGES_REQUESTED** [review]
Why a 6000XE and APX6000XE directory?
Check other comments as well

**Comment by Imwhattherel** [comment]
> Why a 6000XE and APX6000XE directory? Check other comments as well
Didn’t add at first. Didn’t notice that it added

**Comment by Imwhattherel** [comment]
should be good to go now

**Comment by Imwhattherel** [comment]
added a fix for 6kxe being off center

**Review by firealarmss — APPROVED** [review]
Will approve, will make a couple changes once merged.

**Pull request merged**
